# Generated by Django 6.0.6 on 2026-06-21 13:25

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videofile',
            name='quality',
            field=models.CharField(choices=[('HD', 'HD'), ('FHD', 'FHD'), ('UHD', 'UHD')], default='HD', max_length=3),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['video', 'user', 'created_at'], name='api_like_video_i_79c64a_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['owner'], name='api_video_owner_i_33ca9a_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['created_at'], name='api_video_created_061a23_idx'),
        ),
        migrations.AddIndex(
            model_name='videofile',
            index=models.Index(fields=['video'], name='api_videofi_video_i_4c30be_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('video', 'user'), name='unique_video_user_like'),
        ),
    ]
